receivers:
  mongodbatlas:
    public_key: gmxaumln
    private_key: f5b31bd6-81c4-46a4-a0b5-f15bd1d6645d
    projects:                    # Required: List of projects to collect metrics from
      - name:  "James Osgood Demo Project"       # Replace with valid MongoDB Atlas project ID

exporters:
  debug:
    verbosity: detailed

  # otlphttp/prometheus:
  #   endpoint: "http://prometheus:9090/api/v1/otlp"
  #   tls:
  #     insecure: true
  
  prometheus:
    endpoint: "otel_collector_atlas:9091"
    const_labels:
        source: jco
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]
      exporters: [prometheus, debug]

