receivers:
  mongodbatlas:
    public_key: <public_key> # Required: Public key for the MongoDB Atlas API
    private_key: <private_key> # Required: Private key for the MongoDB Atlas API
    granularity : PT10S
    projects:                    # Required: List of projects to collect metrics from
      - name:  "James Osgood Demo Project"       # Replace with valid MongoDB Atlas project ID
        include_clusters: [mon-test]

exporters:
  debug:
    verbosity: detailed

  prometheus:
    endpoint: "otel_collector_atlas:9091"
    send_timestamps: true
    metric_expiration: 180m
    enable_open_metrics: true
    add_metric_suffixes: false
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [mongodbatlas]
      exporters: [prometheus, debug]

