global:
  evaluation_interval: 30s
  scrape_interval: 6s
storage:
  tsdb:
    out_of_order_time_window: 30m
scrape_configs:
- job_name: otel-collector
  static_configs:
  - targets:
    - 'otel_collector_atlas:8888'
    - 'otel_collector_atlas:9091'
